---
title: "Forecast_Additional_Models"
author: "Justin Maynard"
date: "2025-03-31"
output: pdf_document
always_allow_html: true
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: sentence
---

## Setting R code chunk options

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

## Loading packages and initializing

```{r package, message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)
library(openxlsx)
library(here)
library(tseries)

```

## Import and transform load data

```{r}
#Import hourly load data
load_data <- read_excel("data/load.xlsx")

#Convert to daily average load
load_daily <- load_data %>%
  mutate(DailyLoad = rowMeans(select(., h1:h24), na.rm = TRUE)) %>%
  select(date, DailyLoad)

summary(load_daily)

#Transforming into time series objects
load_daily_ts <- msts(load_daily$DailyLoad,
                start = c(2005, 1, 1),
                seasonal.periods = c(7, 365.25))

#Plot the time series
autoplot(load_daily_ts) +
  labs(title = "Daily Electricity Load Time Series")

#Decompose daily load time series
load_daily_ts %>% mstl() %>%
  autoplot()

```

## Prepare training and test sets

```{r}
#Create a subset for training purpose from 2005-01-01 to 2009-12-31
n_for = 59

load_daily_train_ts <- subset(load_daily_ts, end = length(load_daily_ts) - n_for)

#Create a subset for testing purpose from 2010-01-01 to 2010-02-28
load_daily_test_ts   <- subset(load_daily_ts, start = length(load_daily_ts) - n_for + 1)


#Plot training and testing sets
autoplot(load_daily_train_ts)
autoplot(load_daily_test_ts)
```

## Modles:
SARIMA, ARIMA + Fourier, STL + ETS, BSM, TBATS, NNETAR

## Model 1 - Naive

```{r}
#Fit naive model to training data
naive_model <- naive(load_daily_train_ts, h = n_for)

#Plot forecast vs actual
autoplot(naive_model) +
  autolayer(load_daily_test_ts, series = "Actual", color = "red") +
  labs(title = "Naive Forecast vs Actual 2010 Jan–Feb",
       y = "Daily Load")

#Refit model on full dataset
naive_model_full <- naive(load_daily_ts, h = n_for)
str(naive_model_full)

#Extract forecast values
forecast_2011_model_1 <- as.numeric(naive_model_full$mean)

```

## Model 2 - STL + ETS

```{r}

ETS_fit <- stlf(load_daily_train_ts, h = n_for)

autoplot(ETS_fit) + ylab("Daily Demand")

#plot with full data
autoplot(load_daily_ts) + 
  autolayer(ETS_fit, series = "STL + ETS", PI = FALSE)

#fit on full dataset
ETS_full <- stlf(load_daily_ts, h = n_for)
str(ETS_full)

#accuracy
ETS_scores <- accuracy(ETS_fit$mean, load_daily_test_ts)

forecast_2011_model_2 <- as.numeric(ETS_full$mean)

#Read submission template
template <- read_excel("data/submission_template.xlsx")

#Insert forecast
template$load <- forecast_2011_model_2

#Save as CSV
write.csv(template, "forecasts/forecast_submission_model_2.csv", row.names = FALSE)

```

## Model 3 - ARIMA + FOURIER terms

```{r}

k = c(2,6)

ARIMA_Fourier_Fit <- auto.arima(load_daily_train_ts,
                                seasonal = FALSE,
                                lambda = 0,
                                xreg = fourier(load_daily_train_ts,
                                               K = k))

ARIMA_Fourier_Forecast <- forecast(ARIMA_Fourier_Fit,
                                   xreg = fourier(load_daily_train_ts,
                                                  K = k,
                                                  h = n_for),
                                   h = n_for)

autoplot(ARIMA_Fourier_Forecast) 

autoplot(load_daily_ts) + 
  autolayer(ARIMA_Fourier_Forecast, series = "ARIMA_FOURIER", PI = FALSE)


```

```{r}
#Fit on full dataset

ARIMA_Fourier_Fit_Full <- auto.arima(load_daily_ts,
                                seasonal = FALSE,
                                lambda = 0,
                                xreg = fourier(load_daily_ts,
                                               K = k))

ARIMA_Fourier_Forecast_Full <- forecast(ARIMA_Fourier_Fit_Full,
                                   xreg = fourier(load_daily_ts,
                                                  K = k,
                                                  h = n_for),
                                   h = n_for)

str(ARIMA_Fourier_Forecast_Full)

forecast_2011_model_3 <- as.numeric(ARIMA_Fourier_Forecast_Full$mean)

#Read submission template
template <- read_excel("data/submission_template.xlsx")

#Insert forecast
template$load <- forecast_2011_model_3

#accuracy
ARIMA_Fourier_scores <- accuracy(ARIMA_Fourier_Forecast$mean, load_daily_test_ts)

#Save as CSV
write.csv(template, "forecasts/forecast_submission_model_3.csv", row.names = FALSE)

```


## Model 4 - SARIMA


## Model 5 - TBATS

```{r}

#Fit on training data
TBATS_fit <- tbats(load_daily_train_ts)

TBATS_forecast <- forecast(TBATS_fit, h = n_for)


autoplot(TBATS_forecast) 

autoplot(load_daily_ts) + 
  autolayer(TBATS_forecast, series = "TBATS", PI = FALSE)

TBATS_scores <- accuracy(TBATS_forecast$mean, load_daily_test_ts)


#Fit on full data
TBATS_full <- tbats(load_daily_ts)
TBATS_forecast_full <- forecast(TBATS_full, h = n_for)

forecast_2011_model_5 <- as.numeric(TBATS_forecast_full$mean)

#Read submission template
template <- read_excel("data/submission_template.xlsx")

#Insert forecast
template$load <- forecast_2011_model_5

#Save as CSV
write.csv(template, "forecasts/forecast_submission_model_5.csv", row.names = FALSE)

```


## Model 6 - BSM

```{r}
#variances for level, trend, seasonal, observation

BSM_fit <- StructTS(load_daily_test_ts, type = "BSM")

checkresiduals(BSM_fit)

BSM_forecast <- forecast(BSM_fit, h = n_for)
autoplot(BSM_forecast) 

autoplot(load_daily_ts) + 
  autolayer(BSM_forecast, series = "BSM", PI = FALSE)

```


## Model 7 - NNETAR

```{r}

NN_fit <- nnetar(load_daily_train_ts,
                 p = 1,
                 P = 0,
                 xreg = fourier(load_daily_train_ts, K=c(2,12)))

NN_forecast <- forecast(NN_fit, h = n_for, 
                 xreg = fourier(load_daily_train_ts, 
                                K = c(2,12),
                                h = n_for))
checkresiduals(NN_forecast)



autoplot(NN_forecast)

autoplot(load_daily_ts) + 
  autolayer(NN_forecast, series = "NNETAR", PI = FALSE)

NN_scores <- accuracy(NN_forecast$mean, load_daily_test_ts)

```


```{r}



#Fit on full data
NN_fit_full <- nnetar(load_daily_ts,
                 p = 1,
                 P = 0,
                 xreg = fourier(load_daily_ts, K=c(2,12)))

NN_forecast_full <- forecast(NN_fit_full, h = n_for, 
                 xreg = fourier(load_daily_ts, 
                                K = c(2,12),
                                h = n_for))

forecast_2011_model_7 <- as.numeric(NN_forecast_full$mean)
#Read submission template
template <- read_excel("data/submission_template.xlsx")

#Insert forecast
template$load <- forecast_2011_model_7

#Save as CSV
write.csv(template, "forecasts/forecast_submission_model_7.csv", row.names = FALSE)
```



```{r}
grid_week <- 1:3
grid_year <- 4:15
results <- data.frame()


for (K_w in grid_week) {
  for (K_y in grid_year) {
    K_vec  <- c(K_w, K_y)
    fit    <- nnetar(load_daily_train_ts, p = 1, P = 0,
                     xreg = fourier(load_daily_train_ts, K = K_vec))
    fc     <- forecast(fit, h = n_for,
                       xreg = fourier(load_daily_train_ts, K = K_vec, h = n_for))
    rmse   <- accuracy(fc, load_daily_test_ts)["Test set", "RMSE"]
    results<- rbind(results,
                    data.frame(K_week = K_w, K_year = K_y, RMSE = rmse))
  }
}

best_K <- results[which.min(results$RMSE), c("K_week","K_year")]
print(best_K)

```


```{r}


#Fit on full data
NN_fit_full <- nnetar(load_daily_ts,
                 p = 1,
                 P = 0,
                 xreg = fourier(load_daily_ts, K=c(3,15)))

NN_forecast_full <- forecast(NN_fit_full, h = n_for, 
                 xreg = fourier(load_daily_ts, 
                                K = c(3,15),
                                h = n_for))

forecast_2011_model_8 <- as.numeric(NN_forecast_full$mean)
#Read submission template
template <- read_excel("data/submission_template.xlsx")

#Insert forecast
template$load <- forecast_2011_model_8

#Save as CSV
write.csv(template, "forecasts/forecast_submission_model_8.csv", row.names = FALSE)
```


## Scenario Generation

```{r}

temperature <- read_excel("data/temperature.xlsx")

```


